<?php

namespace Database\Seeders;

use App\Models\Subject;
use Illuminate\Database\Console\Seeds\WithoutModelEve8s;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $grade1 = json_encode([
            array("id" => "1", "name" => "Pre-K"),
            array("id" => "2", "name" => "K"),
            array("id" => "3", "name" => "1"),
            array("id" => "4", "name" => "2"),
            array("id" => "5", "name" => "3"),
            array("id" => "6", "name" => "4"),
            array("id" => "7", "name" => "5"),
            array("id" => "8", "name" => "6"),
        ]);
        $grade2 = json_encode([
            array("id" => "9", "name" => "7"),
            array("id" => "10", "name" => "8"),
            array("id" => "11", "name" => "9"),
            array("id" => "12", "name" => "10")
        ]);
        $grade3 = json_encode([
            array("id" => "13", "name" => "11"),
            array("id" => "14", "name" => "12"),
            array("id" => "15", "name" => "Other")
        ]);

        $now = Carbon::now()->toDateTimeString();
        Subject::insert([
            // NSW subject
            ['state_id' => '1', 'grades' => $grade1, 'name' => 'Primary School General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade1, 'name' => 'Primary School English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade1, 'name' => 'Primary School Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade1, 'name' => 'OC Exam Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade1, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade1, 'name' => 'HAST Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade1, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade2, 'name' => 'Yrs 7-10 General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade2, 'name' => 'Yrs 7-10 English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade2, 'name' => 'Yrs 7-10 Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade2, 'name' => 'Yrs 7-10 Science', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade2, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade2, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC English (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC English (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC English Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC English Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC Maths (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC Maths (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC Maths Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC Maths Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC Chemistry', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC Biology', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC Physics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC Business Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC Legal Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '1', 'grades' => $grade3, 'name' => 'HSC Economics', 'created_at' => $now, 'updated_at' => $now],
            // QLD subject
            ['state_id' => '3', 'grades' => $grade1, 'name' => 'Primary School General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade1, 'name' => 'Primary School English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade1, 'name' => 'Primary School Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade1, 'name' => 'OC Exam Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade1, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade1, 'name' => 'HAST Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade1, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade2, 'name' => 'Yrs 7-10 General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade2, 'name' => 'Yrs 7-10 English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade2, 'name' => 'Yrs 7-10 Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade2, 'name' => 'Yrs 7-10 Science', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade2, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade2, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE General Mathematics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE Mathematical Methods', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE Specialist Mathematics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE Esse8ial Mathematics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE English & Literature Extension', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE Literature', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE Esse8ial English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE Physics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE Biology', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE Chemistry', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '3', 'grades' => $grade3, 'name' => 'QCE General Support', 'created_at' => $now, 'updated_at' => $now],
            // VIC subject
            ['state_id' => '2', 'grades' => $grade1, 'name' => 'Primary School General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade1, 'name' => 'Primary School English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade1, 'name' => 'Primary School Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade1, 'name' => 'OC Exam Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade1, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade1, 'name' => 'HAST Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade1, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade2, 'name' => 'Yrs 7-10 General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade2, 'name' => 'Yrs 7-10 English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade2, 'name' => 'Yrs 7-10 Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade2, 'name' => 'Yrs 7-10 Science', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade2, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade2, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE Foundation Mathematics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE Further Mathematics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE General Mathematics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE Mathematical Methods', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE Specialist Mathematics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE English Language', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE Foundation English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE Literature', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE Physics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE Biology', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE Chemistry', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE Psychology', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '2', 'grades' => $grade3, 'name' => 'VCE General Support', 'created_at' => $now, 'updated_at' => $now],            
            // ACT subject
            ['state_id' => '4', 'grades' => $grade1, 'name' => 'Primary School General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade1, 'name' => 'Primary School English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade1, 'name' => 'Primary School Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade1, 'name' => 'OC Exam Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade1, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade1, 'name' => 'HAST Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade1, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade2, 'name' => 'Yrs 7-10 General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade2, 'name' => 'Yrs 7-10 English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade2, 'name' => 'Yrs 7-10 Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade2, 'name' => 'Yrs 7-10 Science', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade2, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade2, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC English (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC English (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC English Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC English Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC Maths (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC Maths (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC Maths Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC Maths Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC Chemistry', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC Biology', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC Physics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC Business Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC Legal Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '4', 'grades' => $grade3, 'name' => 'HSC Economics', 'created_at' => $now, 'updated_at' => $now],
            // SA subject
            ['state_id' => '5', 'grades' => $grade1, 'name' => 'Primary School General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade1, 'name' => 'Primary School English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade1, 'name' => 'Primary School Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade1, 'name' => 'OC Exam Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade1, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade1, 'name' => 'HAST Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade1, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade2, 'name' => 'Yrs 7-10 General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade2, 'name' => 'Yrs 7-10 English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade2, 'name' => 'Yrs 7-10 Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade2, 'name' => 'Yrs 7-10 Science', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade2, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade2, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC English (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC English (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC English Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC English Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC Maths (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC Maths (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC Maths Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC Maths Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC Chemistry', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC Biology', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC Physics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC Business Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC Legal Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '5', 'grades' => $grade3, 'name' => 'HSC Economics', 'created_at' => $now, 'updated_at' => $now],
            // WA subject
            ['state_id' => '6', 'grades' => $grade1, 'name' => 'Primary School General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade1, 'name' => 'Primary School English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade1, 'name' => 'Primary School Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade1, 'name' => 'OC Exam Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade1, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade1, 'name' => 'HAST Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade1, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade2, 'name' => 'Yrs 7-10 General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade2, 'name' => 'Yrs 7-10 English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade2, 'name' => 'Yrs 7-10 Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade2, 'name' => 'Yrs 7-10 Science', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade2, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade2, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC English (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC English (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC English Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC English Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC Maths (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC Maths (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC Maths Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC Maths Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC Chemistry', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC Biology', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC Physics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC Business Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC Legal Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '6', 'grades' => $grade3, 'name' => 'HSC Economics', 'created_at' => $now, 'updated_at' => $now],
            // TAS subject
            ['state_id' => '7', 'grades' => $grade1, 'name' => 'Primary School General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade1, 'name' => 'Primary School English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade1, 'name' => 'Primary School Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade1, 'name' => 'OC Exam Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade1, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade1, 'name' => 'HAST Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade1, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade2, 'name' => 'Yrs 7-10 General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade2, 'name' => 'Yrs 7-10 English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade2, 'name' => 'Yrs 7-10 Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade2, 'name' => 'Yrs 7-10 Science', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade2, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade2, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC English (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC English (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC English Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC English Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC Maths (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC Maths (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC Maths Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC Maths Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC Chemistry', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC Biology', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC Physics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC Business Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC Legal Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '7', 'grades' => $grade3, 'name' => 'HSC Economics', 'created_at' => $now, 'updated_at' => $now],
            // NT subject
            ['state_id' => '8', 'grades' => $grade1, 'name' => 'Primary School General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade1, 'name' => 'Primary School English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade1, 'name' => 'Primary School Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade1, 'name' => 'OC Exam Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade1, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade1, 'name' => 'HAST Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade1, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade2, 'name' => 'Yrs 7-10 General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade2, 'name' => 'Yrs 7-10 English', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade2, 'name' => 'Yrs 7-10 Maths', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade2, 'name' => 'Yrs 7-10 Science', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade2, 'name' => 'NAPLAN Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade2, 'name' => 'Selective School Preparation', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC English (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC English (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC English Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC English Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC Maths (Standard)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC Maths (Advanced)', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC Maths Extension 1', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC Maths Extension 2', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC General Support', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC Chemistry', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC Biology', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC Physics', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC Business Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC Legal Studies', 'created_at' => $now, 'updated_at' => $now],
            ['state_id' => '8', 'grades' => $grade3, 'name' => 'HSC Economics', 'created_at' => $now, 'updated_at' => $now],
        ]);
    }
}
